### ISSUE TITLE
Warning: The "to" argument must be of type string.

### ISSUE THREAD

**Issue by mkalinowski44** [babel/grunt-babel#99]
Setup:

- Windows 10
- Node v10.15.3
- npm 6.4.1
- yarn 1.16.0
- grunt 1.0.4

Gruntfile.js
```
module.exports = function(grunt) {
   require('load-grunt-tasks')(grunt);

   grunt.initConfig({

    babel: {
         dist: {
            files: {
               'js/app.js': 'js/app-compiled.js'
            }
         }
      },
   });

   grunt.registerTask("build", ["babel",]);
}
```

When i enter "grunt build" i receive respond:
`Warning: The "to" argument must be of type string. Received type undefined Use --force to continue.`
and only this. What is a "to" argument and why it isn't be of type string? After all this is taken from the example and does not work.

**Comment by jgarite** [comment]
facing the same issue
"babel-core": "^6.26.3",
"babel-preset-env": "^1.7.0",
"grunt": "^1.0.3",
"grunt-babel": "^7.0.0"

**Comment by jgarite** [comment]
@RiddickAbaddon I'm not sure if you realized it already, but i realized it shortly after i posted here. The source file was not created. In my case, I was using concat first and the output from concat didnt create a file. therefore, babel didn't find any file to work with. not sure if this is the same issue you have, but once i had the file in place, everything went fine.

**Comment by mread1208** [comment]
I believe the error you're getting is that Babel cannot compile `fileA.js` into `fileB.js` because `fileA.js` doesn't exist.

In the `files` object of the config, the key should be the output file name and the value should be the name of the file you want converted (seems backwards, but it makes sense if you look at it this way). 

So in your example:
```
files: {
    'js/app.js': 'js/app-compiled.js'
}
```
You're trying to convert a file called `js/app-compiled.js` into `js/app.js`.  I believe you have these backwards, you should have a file called `js/app.js` and you want grunt / babel to compile that into a new file called `js/app-compiled.js`.  Update your config to look like this and make sure you have a file called app.js in the correct location:
```
files: {
    'js/app-compiled.js': 'js/app.js'
}
```

**Comment by n-renaud** [comment]
The previous comment solved it for me, wasn't too obvious the format was supposed to be 'destination-name.js : source-name.js'

**Comment by 1deadpixl** [comment]
In summary: this error is talking about the source file. If the error states that received type is `undefined` then it couldn't find the source file you specified. As with the other commenters, it's usually a matter of double-checking that your path string is correct. In my case, I was skipping over a subdirectory—added it an fixed the problem.

**Comment by vxidfunctixn** [comment]
Yes, this is it. I confused the name of the source file with the resulting one. Thank you all
